# Generated by Django 3.0.2 on 2020-03-06 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20200303_2102'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reps', models.IntegerField(blank=True)),
                ('weight', models.FloatField(blank=True)),
                ('unit', models.CharField(blank=True, choices=[('lbs', 'lbs'), ('kg', 'kg')], default='lbs', max_length=3)),
                ('difficulty', models.CharField(blank=True, choices=[('E', 'Easy'), ('M', 'In the middle'), ('H', 'Hard')], default='Easy', max_length=1)),
                ('distance', models.IntegerField(blank=True)),
                ('distance_unit', models.CharField(blank=True, choices=[('mi', 'mi'), ('km', 'km')], default='mi', max_length=2)),
                ('time', models.FloatField(blank=True)),
                ('time_unit', models.CharField(blank=True, choices=[('sec', 'sec'), ('min', 'min')], default='sec', max_length=3)),
                ('notes', models.CharField(blank=True, max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Exercise')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Log')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reps', models.IntegerField(blank=True)),
                ('weight', models.FloatField(blank=True)),
                ('unit', models.CharField(blank=True, choices=[('lbs', 'lbs'), ('kg', 'kg')], default='lbs', max_length=3)),
                ('difficulty', models.CharField(blank=True, choices=[('E', 'Easy'), ('M', 'In the middle'), ('H', 'Hard')], default='Easy', max_length=1)),
                ('distance', models.IntegerField(blank=True)),
                ('distance_unit', models.CharField(blank=True, choices=[('mi', 'mi'), ('km', 'km')], default='mi', max_length=2)),
                ('time', models.FloatField(blank=True)),
                ('time_unit', models.CharField(blank=True, choices=[('sec', 'sec'), ('min', 'min')], default='sec', max_length=3)),
                ('notes', models.CharField(blank=True, max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.ExerciseByGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cardiosethistory',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='cardiosethistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='liftingset',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='liftingset',
            name='log',
        ),
        migrations.RemoveField(
            model_name='liftingset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='liftingsethistory',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='liftingsethistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='CardioSet',
        ),
        migrations.DeleteModel(
            name='CardioSetHistory',
        ),
        migrations.DeleteModel(
            name='LiftingSet',
        ),
        migrations.DeleteModel(
            name='LiftingSetHistory',
        ),
    ]
