# Generated by Django 3.0.2 on 2020-03-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20200312_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
