# Generated by Django 3.0.2 on 2020-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20200312_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
