# Generated by Django 3.0.2 on 2020-03-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20200312_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'In the middle'), ('H', 'Hard')], default='Easy', max_length=1),
        ),
        migrations.AlterField(
            model_name='set',
            name='distance_unit',
            field=models.CharField(choices=[('mi', 'mi'), ('km', 'km')], default='mi', max_length=2),
        ),
        migrations.AlterField(
            model_name='set',
            name='time_unit',
            field=models.CharField(choices=[('sec', 'sec'), ('min', 'min')], default='sec', max_length=3),
        ),
        migrations.AlterField(
            model_name='set',
            name='unit',
            field=models.CharField(choices=[('lbs', 'lbs'), ('kg', 'kg')], default='lbs', max_length=3),
        ),
        migrations.AlterField(
            model_name='sethistory',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'In the middle'), ('H', 'Hard')], default='Easy', max_length=1),
        ),
        migrations.AlterField(
            model_name='sethistory',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sethistory',
            name='distance_unit',
            field=models.CharField(choices=[('mi', 'mi'), ('km', 'km')], default='mi', max_length=2),
        ),
        migrations.AlterField(
            model_name='sethistory',
            name='notes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sethistory',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sethistory',
            name='time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sethistory',
            name='time_unit',
            field=models.CharField(choices=[('sec', 'sec'), ('min', 'min')], default='sec', max_length=3),
        ),
        migrations.AlterField(
            model_name='sethistory',
            name='unit',
            field=models.CharField(choices=[('lbs', 'lbs'), ('kg', 'kg')], default='lbs', max_length=3),
        ),
        migrations.AlterField(
            model_name='sethistory',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
