# Generated by Django 3.0.2 on 2020-03-03 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseByGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHEST', 'CHEST'), ('BACK', 'BACK'), ('ARMS', 'ARMS'), ('LEGS', 'LEGS'), ('ABS', 'ABS'), ('CARDIO', 'CARDIO')], max_length=15)),
                ('exercise_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=30)),
                ('workout_desc', models.TextField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('CHEST', 'CHEST'), ('BACK', 'BACK'), ('ARMS', 'ARMS'), ('LEGS', 'LEGS'), ('ABS', 'ABS'), ('CARDIO', 'CARDIO')], max_length=15)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.ExerciseByGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Workout')),
            ],
        ),
    ]
