# Generated by Django 3.0.2 on 2020-03-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
    ]
