# Generated by Django 2.0.6 on 2020-03-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20200303_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisebygroup',
            name='type',
            field=models.CharField(choices=[('CHEST', 'CHEST'), ('BACK', 'BACK'), ('ARMS', 'ARMS'), ('LEGS', 'LEGS'), ('ABS', 'ABS'), ('SHOULDERS', 'SHOULDERS'), ('CARDIO', 'CARDIO')], max_length=15),
        ),
    ]
