# Generated by Django 3.0.2 on 2020-05-26 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20200428_1557'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onerepmax',
            name='exercise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workout.ExerciseByGroup'),
        ),
        migrations.AlterField(
            model_name='onerepmax',
            name='unit',
            field=models.CharField(choices=[('lbs', 'lbs'), ('kg', 'kg')], max_length=3),
        ),
    ]
