# Generated by Django 3.0.2 on 2020-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200526_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onerepmax',
            name='unit',
            field=models.CharField(choices=[('lbs', 'lbs'), ('kg', 'kg')], default='lbs', max_length=3),
        ),
    ]
